name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Ver arquivos do projeto
        run: ls -la

      - name: Aceitar licenças Android SDK
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Instalar SDK necessário
        run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Build APK Debug
        run: gradle :app:assembleDebug --stacktrace --info --no-daemon
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Procurar APK gerado
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TacadinhaAim-APK
          path: "**/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
